version: "3.8"

services:
  postgresdb:
    image: postgres:15.2
    container_name: postgresdb
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-kulkeez}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-mydb}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped